Add prettier
lncapital/torq pull request #102
Opened 2022-09-27 18:09 UTC by cryptosalomao

Initial setup for prettier and rules for code style enforcement

2022-09-28 14:11 UTC, maxwedwards requested changes
We have been living with just using prettier in the editor but I can see the benefit of having the script installed. Please can we just stick to the prettier defaults though?

2022-09-28 14:11 UTC, maxwedwards commented on web/package.json
> +    "lint": "eslint --ignore-path .eslintignore --fix --ext .js,.ts,.tsx,.jsx .",
Linting is part of `make test` and I would prefer that `make test` does not modify the source code. I think we can achieve the same goal with the format script by having it be `"npm run prettier && npm run lint -- --fix"`

2022-09-28 14:11 UTC, maxwedwards commented on web/package.json
> +    "format": "npm run prettier && npm run lint",
```suggestion
    "format": "npm run prettier && npm run lint -- --fix",
```

2022-09-30 16:53 UTC, cryptosalomao commented
As discussed with @ohenrik, I'm going to close this PR for now and work on a new one addressing the target for having prettier working alongside eslint.

2022-09-30 16:53 UTC, closed without merging