connect peer
lncapital/torq pull request #161
Opened 2022-10-13 17:51 UTC by iulian-moraru

connect peer & list peers endpoint
connect peer when opening channel

2022-10-13 21:45 UTC, maxwedwards commented on internal/channels/open_channel.go
> +			}
Rather than using `strings.Contains` can you see if you could use `errors.Is` or `errors.As`. Give me a shout if you want a hand with that. Also the rest of the error handling seems off to me. If you are logging + sending a custom error down the websocket, why are we also returning the error? What will the calling function do with that error? Something seems off there. Again, give me a shout if you want to talk it through.

2022-10-13 21:47 UTC, maxwedwards commented on internal/channels/open_channel.go
> +		return err
throw in an `return errors.Wrap(err, "Listing Peers")`?

2022-10-13 21:47 UTC, maxwedwards commented on internal/channels/open_channel.go
> +		return err
throw in an `return errors.Wrap(err, "Connect Peer")`?

2022-10-13 21:50 UTC, maxwedwards commented on internal/peers/connect_peer.go
> +		return "", err
error wrap with "process request"

2022-10-13 21:50 UTC, maxwedwards commented on internal/peers/connect_peer.go
> +		if strings.Contains(err.Error(), "already connected") {
Same as above, can you try to use `errors.Is` or `errors.As`

2022-10-13 21:53 UTC, maxwedwards commented on internal/peers/connect_peer.go
> +		return lnrpc.ConnectPeerRequest{}, errors.Wrap(err, "Missing LND Address or Host")
again, err is nil so use `errors.New()` and explain what's wrong with having either pubKey or Host to be empty string

2022-10-13 21:58 UTC, maxwedwards commented on internal/peers/list_peers.go
> +	}
Can you talk me through what this is about?

2022-10-13 22:02 UTC, maxwedwards commented on internal/peers/handlers.go
> +	r.GET("list/:nodeId/*le", func(c *gin.Context) { listPeersHandler(c, db) })
These routes aren't looking very RESTful. Can the add just be a POST to `/api/peers` and not `/api/peers/add` so just make this `r.POST("", func(....`.

And the list, shouldn't that be a URL like `/api/peers?localNodeId=1&le=blabla`?

2022-10-13 22:06 UTC, maxwedwards requested changes
Very good, just a few comments. Get in touch if something doesn't make sense.

2022-10-14 18:10 UTC, iulian-moraru commented on internal/channels/open_channel.go
> +		return err
list peers already returns errors.Wrap(err, "Listing Peers")

2022-10-14 18:12 UTC, iulian-moraru commented on internal/channels/open_channel.go
> +		return err
ConnectPeer already returns errors.Wrap(err, "Connect Peer")

2022-10-17 16:42 UTC, maxwedwards commented
Error handling isn't quite right still. The errors.Is() call won't work like that with a string. It needs to have an error value, please verify for yourself that the errors.Is call is actually working as intended.

Have a look at this for examples of using errors.Is and errors.As: https://gosamples.dev/check-error-type/.

I've also published a guide to error handling in the Torq codebase: https://github.com/lncapital/torq/blob/main/docs/go_error_handling.md

As for your comments on not wrapping, I still think it would be best and you can differentiate them by for example having one being "Connect Peer" and the other being "LND: Connect peer" as the one is an internal function call and the other is to LND's api.

2022-10-17 16:42 UTC, maxwedwards requested changes
Comments as above

2022-10-19 11:13 UTC, merged