split channel route
lncapital/torq pull request #173
Opened 2022-10-19 16:14 UTC by kevenboo

Missing:
- Change payload to Camel
- Clanup comments
- Adapt frontend to new endpoints

2022-10-25 13:34 UTC, 2Fast2BCn requested changes
Looks very good I only saw some minor inconsistencies. I'm not sure they all need to be addressed but I just noticed the ones I could found.

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/channel_balance.go
> +	LNDShortChannelId string     `json:"LndShortChannelId"`
`json:"LndShortChannelId"` should be camelCase so `json:"lndShortChannelId"`

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +func getChannelFrom(queryFrom string) (time.Time, error) {
I cannot seem to find where these 3 methods are actually referenced.

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +		server_errors.LogAndSendServerError(c, err)
I think we decided to use the following for parameter handlers. (same for parameter to)
`server_errors.SendBadRequest(c, "Failed to find/parse ... in the request.")`

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +	from, err := time.Parse("2006-01-02", c.Query("from"))
I think we decided to use the following for parameter handlers. (same for parameter to)
server_errors.SendBadRequest(c, "Failed to find/parse ... in the request.")

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +	ChannelBalances []*ChannelBalance `json:"channelBalance"`
`json:"channelBalance"` should that be `json:"channelBalances"` (with an s) to keep it consistent?

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +			cb, err := getChannelBalance(db, string(chanId), from, to)
`string(chanId)` it already is a string ?

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +	if chanIds[0] != "1" {
shouldn't this be `if chanIds[0] != "" {`

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +		server_errors.LogAndSendServerError(c, err)
I think we decided to use the following for parameter handlers. (same for parameter to)
server_errors.SendBadRequest(c, "Failed to find/parse ... in the request.")

2022-10-25 13:34 UTC, 2Fast2BCn commented on internal/channel_history/handlers.go
> +	RebalancingDetails RebalancingDetails `json:"rebalancing"`
Not sure if it's important but the name is inconsistent here `json:"rebalancing"` instead of `json:"rebalancingDetails"`

2022-10-25 13:34 UTC, 2Fast2BCn commented on web/src/apiSlice.ts
> +    getFlow: builder.query<any, GetChannelHistoryQueryParams>({
There is an `any` here not sure if it needs to be addressed now or when we refactor the `any`'s in bulk

2022-10-25 16:09 UTC, maxwedwards commented on internal/channel_history/handlers.go
> +		server_errors.LogAndSendServerError(c, err)
Agree, @kevenboo we have 2 new error types in server_errors. BadRequest (400) when you can't parse the request (like here) and Unprocessable Entity (422) when there is a validation failure or an Id is zero rather than a valid id for example. In the future hopefully we will respond differently on the front end based on these codes.

2022-10-25 16:18 UTC, maxwedwards commented on web/src/features/channel/ChannelPage.tsx
> +  const event = clone<ChannelEventResponse>(eventResponse as ChannelEventResponse) || null;
This doesn't look quite right to me, we shouldn't need to make clones of the data. Few extra notes also, we should prefer using `undefined` over `null` and there shouldn't be logic in the main component outside of a hook such as useEffect.

Can you talk me through why you are cloning the data rather than just using the response?

2022-10-25 16:20 UTC, maxwedwards commented on web/src/features/channel/DashboardPage.tsx
> +  const rebalancing = clone<ChannelRebalancingResponse>(rebalancingResponse as ChannelRebalancingResponse) || null;
Same comment as above on the clones.

2022-10-25 16:30 UTC, maxwedwards commented on web/src/utils/queryParamsBuilder.ts
> +};
I'm not a fan of this, what do we do if we go another level deep? `suffixSuffixEndpoint`? I see that you are operating inside the constraints of the existing function but I think this function needs to change to something more flexible. I wouldn't hold up this PR for this and will discuss it as part of the team.

2022-10-25 16:31 UTC, maxwedwards reviewed
Nice PR! Just a few extra comments in addition to @2Fast2BCn. Happy to talk about any of it on slack or call.

2022-10-27 09:07 UTC, kevenboo commented on internal/channel_history/channel_balance.go
> +	LNDShortChannelId string     `json:"LndShortChannelId"`
Fixed

2022-10-31 13:01 UTC, merged