Workflow node for rebalancing
lncapital/torq pull request #447
Opened 2023-02-17 12:03 UTC by 2Fast2BCn

2023-02-18 18:36 UTC, ohenrik requested changes
Before we merge this in we need to think about existing workflows. We need to:
1. Migrate all workflows to use a data source (or remove link to the triggers).
2. Disable all workflows
3. Add version information to Intercom so that we can show an alert to users who upgrades that they need to check their workflows.
4. Push all workflow nodes 400px to the right (to simplify adding data source)

These are known changes, so I'm just adding this list here so we don't forget.

2023-02-20 17:27 UTC, maxwedwards commented on internal/channels/update_channel.go
> +	time.AfterFunc(commons.LIGHTNING_COMMUNICATION_TIMEOUT_SECONDS*time.Second, func() {
This doesn't look safe to me. Normally we would use a context for cancelling something. This doesn't appear to cancel the original job but instead tries to get in there first and write to the response channel. The original job is still going to send something down the channel and what happens then?

2023-02-20 17:31 UTC, maxwedwards commented on internal/automation/managedRebalance.go
> +		fallthrough
No need for fallthrough, it will do unnecessary work.

2023-02-20 18:01 UTC, maxwedwards commented on internal/automation/managedRebalance.go
> +	rebalancers := make(map[commons.RebalanceRequestOrigin]map[int]map[int]*Rebalancer)
Reading through some code I think it might be useful to use specific types even if they are only aliases for int as the key on maps to help the reader know what it's a map of. Especially like in this instance where it's a map of map.

2023-02-20 18:14 UTC, maxwedwards commented on internal/automation/managedRebalance.go
> +				for i := len(rebalanceResults) - 1; i >= 0; i-- {
Probably worth explaining why you have to iterate in reverse

2023-02-20 18:18 UTC, maxwedwards commented on internal/automation/managedRebalance.go
>  func ManagedRebalanceCache(ch chan ManagedRebalance, ctx context.Context) {
Why do we need a cache? Would it be possible to do single threaded or using postgres?

2023-02-20 18:39 UTC, maxwedwards commented
I know this appears to have been merged in already but we should come up with an alternative way to trigger rebalances rather than add more things to the pub sub system.

2023-02-20 18:54 UTC, maxwedwards commented
Again already merged in but `commons.REBALANCE_MAXIMUM_CONCURRENCY`,	`commons.REBALANCE_RUNNER_TIMEOUT_SECONDS`, `commons.REBALANCE_ROUTES_TIMEOUT_SECONDS`, `commons.REBALANCE_PAY_TIMEOUT_SECONDS` do these things need to be in commons? They seem like they only apply here.

Ideally commons wouldn't exist at all, if it has to exist then it should have the minimum amount of things in it.

2023-02-26 17:06 UTC, 2Fast2BCn commented on internal/channels/update_channel.go
> +	time.AfterFunc(commons.LIGHTNING_COMMUNICATION_TIMEOUT_SECONDS*time.Second, func() {
Removed all buffered channels and replaced this section with a loop in PR: https://github.com/lncapital/torq/pull/470

2023-02-26 19:46 UTC, 2Fast2BCn commented
> Again already merged in but `commons.REBALANCE_MAXIMUM_CONCURRENCY`, `commons.REBALANCE_RUNNER_TIMEOUT_SECONDS`, `commons.REBALANCE_ROUTES_TIMEOUT_SECONDS`, `commons.REBALANCE_PAY_TIMEOUT_SECONDS`, `commons.REBALANCE_QUEUE_TICKER_SECONDS ` do these things need to be in commons? They seem like they only apply here.
> 
> Ideally commons wouldn't exist at all, if it has to exist then it should have the minimum amount of things in it.

Must be from my Java background. I'm used to centralizing all static parameters into a "Class" so you have a good overview without having to look for them in different packages of the source tree. If the code convention in golang is different then I'll relocate those into their own packages.

2023-02-27 09:07 UTC, 2Fast2BCn commented on internal/automation/managedRebalance.go
> +	rebalancers := make(map[commons.RebalanceRequestOrigin]map[int]map[int]*Rebalancer)
That is a very good idea!

2023-02-27 09:31 UTC, 2Fast2BCn commented on internal/automation/managedRebalance.go
> +				for i := len(rebalanceResults) - 1; i >= 0; i-- {
Added a comment.

2023-02-27 09:34 UTC, 2Fast2BCn commented on internal/automation/managedRebalance.go
> +		fallthrough
I don't understand what you mean here.
It will check if `IncomingChannelId` and `OutgoingChannelId` are both 0?

2023-02-27 11:07 UTC, maxwedwards commented on internal/automation/managedRebalance.go
> +		fallthrough
What I mean is that fallthrough means it will check the following cases. But if the case WRITE_REBALANCER has matched then the others wont match so why are we checking them?

2023-03-06 15:28 UTC, merged