frontend: use localstorage for global network selection
lncapital/torq pull request #461
Opened 2023-02-21 19:18 UTC by ziggie1984

2023-02-21 19:50 UTC, 2Fast2BCn commented
I haven't looked into the detail of this PR but the services endpoint returns the networks Torq has configuration for, maybe we can incorporate this?

2023-02-22 12:19 UTC, ohenrik requested changes

2023-02-22 12:19 UTC, ohenrik commented on web/src/features/navigation/NetworkSelector.tsx
> +              setItem("activeNetwork", Network.MainNet);
By setting the local storage here we duplicate state, we should either use a middleware or store/restore the local storage through the loading of the network selector in redux or perhaps remove the redux slice for this entierly.

2023-02-22 19:29 UTC, maxwedwards commented
I hope you don't mind but I updated the PR with what I think is a more streamlined way of doing this

2023-02-22 22:14 UTC, ziggie1984 commented
no problem thanks for cleaning this up!

2023-02-22 23:06 UTC, ziggie1984 commented on web/src/features/network/networkSlice.ts
> +  return parseInt(lsActiveNetwork) as Network;
hmm this could lead to a runtime error if the lsActiveNetwork somehow is a string and cannot be parsed as a number?

2023-02-23 12:19 UTC, maxwedwards commented on web/src/features/network/networkSlice.ts
> +  return parseInt(lsActiveNetwork) as Network;
no, it just returns NaN

2023-02-23 12:24 UTC, merged