Feature/add static channel backup endpoint
lncapital/torq pull request #69
Opened 2022-09-17 12:36 UTC by jonassagild

This adds an endpoint for getting a static channel backup. 

A test of the endpoint is missing but will be added.

Happy to receive feedback on anything and everything.

2022-09-22 22:18 UTC, maxwedwards requested changes
Great PR, just a few little things to clean up. I realise some of the problems I've mentioned exist in our codebase elsewhere but we are trying to clean these things up as we go :)

2022-09-22 22:18 UTC, maxwedwards commented on internal/channels/static_channel_backup.go
> +		connectionDetails[0].MacaroonFileBytes)
The api should be told for which node we should connect to rather than hardcoding it to the first one. Probably a query string param.

2022-09-22 22:18 UTC, maxwedwards commented on internal/channels/static_channel_backup.go
> +	}
Functions should generally either log the error OR return it to the caller who can decide what to do with it. In this case simply returning it will allow `getStaticChannelBackupHandler` to log the problem. As it is now it will be logged twice.

Error messages ideally should not use phases such as "can't do x" and "error doing x" and instead should simply say _what_ has just failed such as "Connecting to LND node".

Finally, we should probably wrap the error returned from LND_connect.Connect rather than creating a new error

2022-09-22 22:18 UTC, maxwedwards commented on internal/channels/static_channel_backup.go
> +		return r, err
Again, same comment as above. Either return a (probably wrapped) error or log it, no need for both.

2022-09-22 22:18 UTC, maxwedwards commented on internal/channels/static_channel_backup.go
> +	return staticChannelBackupResp, err
I'd say it would be preferred to explicitly return nil here rather than err even though I know err will be nil. Just makes it clearer that we aren't returning an error.

```suggestion
	return staticChannelBackupResp, nil
```

2022-10-10 07:07 UTC, jonassagild commented
Great feedback, thanks. I will have a look at them shortly!

2022-10-10 07:16 UTC, jonassagild commented on internal/channels/static_channel_backup.go
> +	return staticChannelBackupResp, err
Agree!

2022-10-10 18:09 UTC, maxwedwards commented
@jonassagild let me know when you are ready for this to be re-reviewed

2022-10-12 13:24 UTC, maxwedwards commented
I've marked as draft, just hit "Ready for review" when you want us to take a look

2022-10-24 10:44 UTC, maxwedwards commented
Closing for now, if you wish to continue please feel free to reopen.

2022-10-24 10:44 UTC, closed without merging